In [1]:
import numpy as np
from PIL import Image, ImageOps

import random
import os
import json

## 8 Слайсов

In [2]:
SLICES_CNT = 8
WINDOW_THRESHOLD = 2000
SLICE_THRESHOLD = 1.5 * WINDOW_THRESHOLD
data = np.load(os.path.join('data', 'raw', 'numpy', 'inline_data.npz'))['arr_0']
min_data_value = np.min(data)
max_data_value = np.max(data)
data = (data - min_data_value) / (max_data_value - min_data_value) * 255
labels = np.load(os.path.join('data', 'raw', 'numpy', 'inline_faults_thick_7.npz'))['arr_0']
slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')
print(slices_nums)

[ 10  89 169 249 329 408 488 568]


In [3]:
eval_slices_nums = [50, 200, 370, 520]
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')

In [4]:
WINDOW_SIZE = 512
# WINDOW_THRESHOLD = 700 for thickness 3
WINDOW_THRESHOLD = 2000
WINDOWS_PER_SLICE = 25
SLICES_CNT = 8
SAVE_PATH = os.path.join('data', '512window')

for stage in (['train', 'eval']):
    if stage == 'train':
        slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
    if stage == 'eval':
        slices_nums = eval_slices_nums
    fault_save_path = os.path.join(SAVE_PATH, stage, 'fault')
    seis_save_path = os.path.join(SAVE_PATH, stage, 'seis')
    img_cnt = 0
    metadata = []
    for slice_num in slices_nums:
        data_slice = data[slice_num]
        labels_slice = labels[slice_num]
        timelines, xlines = np.shape(data_slice)
        for _ in range(WINDOWS_PER_SLICE):
            while True:
                random_xline = random.randint(0, xlines - WINDOW_SIZE)
                random_timeline = random.randint(0, timelines - WINDOW_SIZE)
                random_labels_window = labels_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
                if np.sum(random_labels_window) > WINDOW_THRESHOLD:
                    break
            random_data_window = data_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
            metadata.append({
                    'data': f'{img_cnt}.jpeg',
                    'label': f'{img_cnt}.jpeg'
                })
            data_img = ImageOps.grayscale(Image.fromarray(random_data_window))
            label_img = ImageOps.grayscale(Image.fromarray((random_labels_window * 255)))
            data_img.save(os.path.join(seis_save_path, f'{img_cnt}.jpeg'))
            label_img.save(os.path.join(fault_save_path, f'{img_cnt}.jpeg'))
            img_cnt += 1
    with open(os.path.join(SAVE_PATH, stage, 'metadata.json'), 'w') as file:
        json.dump(metadata, file)

## 12 Слайсов

In [2]:
SLICES_CNT = 12
WINDOW_THRESHOLD = 2000
SLICE_THRESHOLD = 1.5 * WINDOW_THRESHOLD
data = np.load(os.path.join('data', 'raw', 'numpy', 'inline_data.npz'))['arr_0']
min_data_value = np.min(data)
max_data_value = np.max(data)
data = (data - min_data_value) / (max_data_value - min_data_value) * 255
labels = np.load(os.path.join('data', 'raw', 'numpy', 'inline_faults_thick_7.npz'))['arr_0']
slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')
print(slices_nums)

[ 10  63 116 169 222 275 329 382 435 488 541 594]


In [3]:
eval_slices_nums = [50, 200, 370, 520]
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')

In [4]:
WINDOW_SIZE = 512
# WINDOW_THRESHOLD = 700 for thickness 3
WINDOW_THRESHOLD = 2000
WINDOWS_PER_SLICE = 25
SLICES_CNT = 12
SAVE_PATH = os.path.join('data', '512window_12slice')

for stage in (['train', 'eval']):
    if stage == 'train':
        slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
    if stage == 'eval':
        slices_nums = eval_slices_nums
    fault_save_path = os.path.join(SAVE_PATH, stage, 'fault')
    seis_save_path = os.path.join(SAVE_PATH, stage, 'seis')
    img_cnt = 0
    metadata = []
    for slice_num in slices_nums:
        data_slice = data[slice_num]
        labels_slice = labels[slice_num]
        timelines, xlines = np.shape(data_slice)
        for _ in range(WINDOWS_PER_SLICE):
            while True:
                random_xline = random.randint(0, xlines - WINDOW_SIZE)
                random_timeline = random.randint(0, timelines - WINDOW_SIZE)
                random_labels_window = labels_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
                if np.sum(random_labels_window) > WINDOW_THRESHOLD:
                    break
            random_data_window = data_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
            metadata.append({
                    'data': f'{img_cnt}.png',
                    'label': f'{img_cnt}.png'
                })
            data_img = ImageOps.grayscale(Image.fromarray(random_data_window))
            label_img = ImageOps.grayscale(Image.fromarray((random_labels_window * 255)))
            data_img.save(os.path.join(seis_save_path, f'{img_cnt}.png'))
            label_img.save(os.path.join(fault_save_path, f'{img_cnt}.png'))
            img_cnt += 1
    with open(os.path.join(SAVE_PATH, stage, 'metadata.json'), 'w') as file:
        json.dump(metadata, file)

## 4 Слайса

In [5]:
SLICES_CNT = 4
WINDOW_THRESHOLD = 2000
SLICE_THRESHOLD = 1.5 * WINDOW_THRESHOLD
data = np.load(os.path.join('data', 'raw', 'numpy', 'inline_data.npz'))['arr_0']
min_data_value = np.min(data)
max_data_value = np.max(data)
data = (data - min_data_value) / (max_data_value - min_data_value) * 255
labels = np.load(os.path.join('data', 'raw', 'numpy', 'inline_faults_thick_7.npz'))['arr_0']
slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')
print(slices_nums)

[ 10 169 329 488]


In [6]:
eval_slices_nums = [50, 200, 370, 520]
for slice_num in slices_nums:
    if np.sum(labels[slice_num]) < SLICE_THRESHOLD:
        print(f'Bad slice №{slice_num}')

In [7]:
WINDOW_SIZE = 512
# WINDOW_THRESHOLD = 700 for thickness 3
WINDOW_THRESHOLD = 2000
WINDOWS_PER_SLICE = 25
SLICES_CNT = 4
SAVE_PATH = os.path.join('data', '512window_4slice')

for stage in (['train', 'eval']):
    if stage == 'train':
        slices_nums = (np.linspace(10, np.shape(labels)[0], SLICES_CNT, endpoint=False, dtype='int'))
    if stage == 'eval':
        slices_nums = eval_slices_nums
    fault_save_path = os.path.join(SAVE_PATH, stage, 'fault')
    seis_save_path = os.path.join(SAVE_PATH, stage, 'seis')
    img_cnt = 0
    metadata = []
    for slice_num in slices_nums:
        data_slice = data[slice_num]
        labels_slice = labels[slice_num]
        timelines, xlines = np.shape(data_slice)
        for _ in range(WINDOWS_PER_SLICE):
            while True:
                random_xline = random.randint(0, xlines - WINDOW_SIZE)
                random_timeline = random.randint(0, timelines - WINDOW_SIZE)
                random_labels_window = labels_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
                if np.sum(random_labels_window) > WINDOW_THRESHOLD:
                    break
            random_data_window = data_slice[random_timeline:random_timeline+WINDOW_SIZE, random_xline:random_xline+WINDOW_SIZE]
            metadata.append({
                    'data': f'{img_cnt}.png',
                    'label': f'{img_cnt}.png'
                })
            data_img = ImageOps.grayscale(Image.fromarray(random_data_window))
            label_img = ImageOps.grayscale(Image.fromarray((random_labels_window * 255)))
            data_img.save(os.path.join(seis_save_path, f'{img_cnt}.png'))
            label_img.save(os.path.join(fault_save_path, f'{img_cnt}.png'))
            img_cnt += 1
    with open(os.path.join(SAVE_PATH, stage, 'metadata.json'), 'w') as file:
        json.dump(metadata, file)